# Generated by Django 4.1.7 on 2023-04-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='expires_at',
        ),
    ]
