# Generated by Django 4.1.5 on 2023-01-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_add',
            field=models.IntegerField(),
        ),
    ]
