# Generated by Django 4.1.5 on 2023-01-15 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_books_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='url_img',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
