# -*- coding: utf-8 -*-
import json

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
from PySide6.QtCore import Slot

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:45.0) Gecko/20100101 Firefox/45.0'
}


class Ui_MainWindow(object):

    def __init__(self):
        self.data = {"title": "Hi"}
        self.iii = 0
        self.select_tasks()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 1001)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 50, 771, 55))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("\n"
                                    "                    padding:40px 10px; \n"
                                    "                    border:1px solid black;\n"
                                    "                ")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 50, 101, 55))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
                                      "                    background-color:white;\n"
                                      "                    border:1px solid black;\n"
                                      "                ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.create_task)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(50, 130, 900, 471))
        self.scrollArea.setStyleSheet("\n"
                                      "                    border:0px solid black;\n"
                                      "                ")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 895, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 890, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 890, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget" + str(self.iii))

        if len(self.data) >= 1:
            self.frame1 = QtWidgets.QFrame(self.verticalLayoutWidget)
            self.frame1.setMinimumSize(QtCore.QSize(100, 60))
            self.frame1.setMaximumSize(QtCore.QSize(16777215, 60))
            self.frame1.setStyleSheet("border:1px solid black;")
            self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
            self.frame1.setObjectName("frame1")
            self.delete_task1 = QtWidgets.QPushButton(self.frame1)
            self.delete_task1.setGeometry(QtCore.QRect(650, 10, 101, 41))
            self.delete_task1.setObjectName("delete_task1")



            self.complete_task1 = QtWidgets.QPushButton(self.frame1)
            self.complete_task1.setGeometry(QtCore.QRect(770, 10, 101, 41))
            self.complete_task1.setObjectName("complete_task1")


            self.label1 = QtWidgets.QLabel(self.frame1)
            self.label1.setGeometry(QtCore.QRect(10, 10, 621, 41))
            self.label1.setStyleSheet("\n"
                                      "border:0px solid black;\n"
                                      "")
            self.label1.setObjectName("label")
            self.verticalLayout.addWidget(self.frame1)
            spacerItem = QtWidgets.QSpacerItem(356, 372, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
            self.verticalLayout.addItem(spacerItem)

            _translate = QtCore.QCoreApplication.translate
            self.delete_task1.setText(_translate("MainWindow", "Удалить"))
            self.complete_task1.setText(_translate("MainWindow", "Выполнить"))
            self.delete_task1.clicked.connect(self.delete_task_f1)  # не работают кнопки
            self.complete_task1.clicked.connect(self.complete_task_f1)  # не работают кнопки
            self.label1.setText(_translate("MainWindow", f"{self.data[0]['task_title']}"))

        # if len(self.data) >= 2:
        #     self.frame2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        #     self.frame2.setMinimumSize(QtCore.QSize(100, 60))
        #     self.frame2.setMaximumSize(QtCore.QSize(16777215, 60))
        #     self.frame2.setStyleSheet("border:1px solid black;")
        #     self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #     self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        #     self.frame2.setObjectName("frame2")
        #     self.delete_task2 = QtWidgets.QPushButton(self.frame2)
        #     self.delete_task2.setGeometry(QtCore.QRect(650, 10, 101, 41))
        #     self.delete_task2.setObjectName("delete_task2")
        #     self.delete_task2.clicked.connect(self.delete_task_f2)
        #     self.complete_task2 = QtWidgets.QPushButton(self.frame2)
        #     self.complete_task2.setGeometry(QtCore.QRect(770, 10, 101, 41))
        #     self.complete_task2.setObjectName("complete_task2")
        #     self.complete_task2.clicked.connect(self.complete_task_f2)
        #     self.label2 = QtWidgets.QLabel(self.frame2)
        #     self.label2.setGeometry(QtCore.QRect(10, 10, 621, 41))
        #     self.label2.setStyleSheet("\n"
        #                               "border:0px solid black;\n"
        #                               "")
        #     self.label2.setObjectName("label")
        #     self.verticalLayout.addWidget(self.frame2)
        #     spacerItem = QtWidgets.QSpacerItem(356, 372, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        #     self.verticalLayout.addItem(spacerItem)
        #
        #     _translate = QtCore.QCoreApplication.translate
        #     self.delete_task2.setText(_translate("MainWindow", "Удалить"))
        #     self.complete_task2.setText(_translate("MainWindow", "Выполнить"))
        #     self.label2.setText(_translate("MainWindow", f"{self.data[0]['task_title']}"))

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ToDo"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ToDo"))

        self.pushButton.setText(_translate("MainWindow", "Создать"))

    @Slot()
    def delete_task_f1(self):
        print("delete_task1")

    def delete_task_f2(self):
        print("delete_task2")

    def delete_task_f3(self):
        print("delete_task3")

    def delete_task_f4(self):
        print("delete_task4")

    def delete_task_f5(self):
        print("delete_task5")

    @Slot()
    def complete_task_f1(self):
        print("complete_task1")

    def complete_task_f2(self):
        print("complete_task2")

    def complete_task_f3(self):
        print("complete_task3")

    def complete_task_f4(self):
        print("complete_task4")

    def complete_task_f5(self):
        print("complete_task5")

    # def look(self):
    #     data = self.data[-1]
    #     self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
    #     self.frame_2.setMinimumSize(QtCore.QSize(100, 60))
    #     self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
    #     self.frame_2.setStyleSheet("border:1px solid black;")
    #     self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    #     self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
    #     self.frame_2.setObjectName("frame_2")
    #     self.delete_task = QtWidgets.QPushButton(self.frame_2)
    #     self.delete_task.setGeometry(QtCore.QRect(650, 10, 101, 41))
    #     self.delete_task.setObjectName("delete_task")
    #     # self.delete_task.clicked.connect(lambda x: delete_task_f(id=data['id']))
    #     # self.delete_task.clicked.connect(self.delete_task)
    #     self.complate_task = QtWidgets.QPushButton(self.frame_2)
    #     self.complate_task.setGeometry(QtCore.QRect(770, 10, 101, 41))
    #     self.complate_task.setObjectName("complate_task")
    #     # self.complate_task.clicked.connect(lambda x: complete_task_f(id=data['id']))
    #     # self.complate_task.clicked.connect(self.complete_task)
    #     self.label = QtWidgets.QLabel(self.frame_2)
    #     self.label.setGeometry(QtCore.QRect(10, 10, 621, 41))
    #     self.label.setStyleSheet("\n"
    #                              "                                        border:0px solid black;\n"
    #                              "                                    ")
    #     self.label.setObjectName("label")
    #     self.verticalLayout.addWidget(self.frame_2)
    #     spacerItem = QtWidgets.QSpacerItem(356, 372, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    #     self.verticalLayout.addItem(spacerItem)
    #
    #     _translate = QtCore.QCoreApplication.translate
    #     self.delete_task.setText(_translate("MainWindow", "Удалить"))
    #     self.complate_task.setText(_translate("MainWindow", "Выполнить"))
    #     self.label.setText(_translate("MainWindow", f"{data['task_title']}"))

    def select_tasks(self):
        response = requests.get(
            url="http://127.0.0.1:8000/todo_app/get_tasks/",
            headers=headers
        )
        # data = json.loads(response.content)
        # self.data = data
        print("select_tasks")
        data = response.text
        print(data)
        print(json.loads(response.text)['response'])
        self.data = json.loads(response.text)['response']

    def create_task(self):
        print("create_task")
        try:
            print(f"http://127.0.0.1:8000/todo_app/create_task/{self.lineEdit.text()}")
            response = requests.post(
                url=f"http://127.0.0.1:8000/todo_app/create_task/{self.lineEdit.text()}",
                data=self.lineEdit.text(),
                headers=headers
            )
            print(response)
            self.select_tasks()
            self.setupUi(MainWindow)
        except Exception as e:
            print(e)


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # + тут ваша логика


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    p = MainWindow()
    p.show()
    sys.exit(app.exec_())
