# Generated by Django 4.1.5 on 2023-01-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('created', models.DateTimeField()),
                ('update', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('id',),
            },
        ),
    ]
