# Generated by Django 4.1.5 on 2023-01-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_alter_tasks_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('id',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
